### PR TITLE
use keyword argments for ruby3 compatibility

### PR DESCRIPTION
**Pull request by g-arjones**
@doudou I have a patch for autoproj ready but we need this for the test suite to pass so I would appreciate it if you could review and release this as soon as you have some time.

Thanks.

### CODE REVIEW

**Comment by doudou** [comment]
Unfortunately this is very likely breaking in numerous ways. The "last arg is keyword arguments" is very unlikely to hold in a lot of cases.

**Comment by g-arjones** [comment]
I tried to properly catch args, kwargs and block [here](https://github.com/doudou/flexmock/blob/master/lib/flexmock/partial_mock.rb#L268) and then propagate them down in an array/hash to `flexmock_invoke_original` [here](https://github.com/doudou/flexmock/blob/master/lib/flexmock/partial_mock.rb#L324). But could not make that work. Thoughts?

**Comment by doudou** [comment]
> Thoughts?

The only way this whole thing will work is by separating positional and keyword arguments everywhere, not by trying to reuse existing hacks (like the "last arg is a hash"). And then fix all the corner cases for 2.7. And make 2.7 the minimum ruby version (I think that last part is more than fair).

I started doing that work, but never committed/finished it. I just pushed it to the 'keyword_argument_support' branch

**Comment by g-arjones** [comment]
[Am I not getting this right or "last arg is a hash" is something that is already assumed?](https://github.com/doudou/flexmock/blob/32c51ef3ee6d4651393bf20d5d8317a459e83d8b/lib/flexmock/validators.rb#L237). If that's the case, wouldn't it be ok to keep the existing hack until proper keyword support is implemented?

> make 2.7 the minimum ruby version

This is a no-go for me. My real goal here is to make autoproj's test suite pass on 3.0 but I still have some projects on 2.5 so if we drop support for 2.5 I will be creating a bigger problem for me than the one I'm trying to solve.

> I started doing that work, but never committed/finished it. I just pushed it to the 'keyword_argument_support' branch

I will have a look and see how much work was left to do.

**Comment by doudou** [comment]
It is what is already assumed, yes. But that was because it was how Ruby was working and therefore it was working. With the separation of keyword from arguments, it won't work in all cases (with no recourse to make it work).

> This is a no-go for me.

I understand, I also have stuff still on 2.5. I was planning to have these stick to an older version of flexmock, for instance by moving flexmock to autoproj's Gemfile and have its version constraint be ruby-version-dependent (there is a minimum_ruby_version specification, but I believe it is broken on the rubygems versions that ships with 2.5, I might be wrong though).

I can't be getting code half-baked solutions in flexmock "just to have autoproj pass". Ultimately, I have a lot of stuff that use flexmock and need to be compatible with ruby 3.0. I know that anything else that explicitly handling keyword arguments won't work.

**Comment by g-arjones** [comment]
OK, you have done most of the work already. There were a few more methods to fix but there's a case I'm not sure backward compatibility can be kept without any hack.

How do you suggest we keep [this test](https://github.com/doudou/flexmock/blob/32c51ef3ee6d4651393bf20d5d8317a459e83d8b/test/should_receive_test.rb#L435) passing now that hashes and kwargs are different things...

**Comment by doudou** [comment]
> How do you suggest we keep [this test](https://github.com/doudou/flexmock/blob/32c51ef3ee6d4651393bf20d5d8317a459e83d8b/test/should_receive_test.rb#L433-L436) passing now that hashes and kwargs are different things?

I don't think it's possible. Or maybe with a feature flag ? I don't remember, but do you think we could handle backward compatibility with 2.5 based on some global flag (if that does not add too much special cases all over the place)

Essentially, as I see it, it might work by  "pushing" keyword arguments to the last positional argument if the flag is set.

This would allow people to slowly migrate to the new behavior without surprises.

What I also do see here is that we would need another predicate, say with_additional_kw_args maybe ? To match the behavior had with hsh(), that is to be allowed to ignore "extra" keyword arguments.

**Comment by g-arjones** [comment]
> Essentially, as I see it, it might work by "pushing" keyword arguments to the last positional argument if the flag is set.

That's what I ultimately decided to do (currently the "flag" is just the ruby version).

> What I also do see here is that we would need another predicate, say with_additional_kw_args maybe ? To match the behavior had with hsh(), that is to be allowed to ignore "extra" keyword arguments.

Yeah, the hsh matcher is the one thing I couldn't get to work properly on ruby < 3 yet. I would like to avoid creating an additional predicate but I'm not sure that will be possible. I will have another look soon.

Also, didn't even try Ruby 2.5 yet. Ruby 2.7 & 3.0 are looking good though.

**Comment by doudou** [comment]
> currently the "flag" is just the ruby version

Make it explicit, and default to "new behavior enabled" only on 3.0 and later (assuming the "old way" works on 2.7)

This will allow people on 2.7 (*cough* me *cough*) to migrate to the new behavior, while still have something that works on 3.0 by default.

**Comment by g-arjones** [comment]
Closing in favor of https://github.com/doudou/flexmock/pull/22

**Pull request closed without merging**
